BEGIN TRANSACTION;
CREATE TABLE users (id INTEGER NOT NULL PRIMARY KEY autoincrement, userName VARCHAR(255) UNIQUE NOT NULL, userPassword CHAR(32) NOT NULL, roleId INTEGER NOT NULL);
DELETE FROM sqlite_sequence;
COMMIT;
