BEGIN TRANSACTION;

CREATE TABLE users (
	id INTEGER NOT NULL PRIMARY KEY autoincrement,
	userName VARCHAR(255) UNIQUE NOT NULL,
	userPassword CHAR(32) NOT NULL,
	roleId INTEGER NOT NULL
);
INSERT INTO "users" VALUES(1, 'admin', '21232f297a57a5a743894a0e4a801fc3', 1);

CREATE TABLE hwServers (
	id INTEGER NOT NULL PRIMARY KEY autoincrement,
	hostName VARCHAR(255) UNIQUE NOT NULL,
	authKey VARCHAR(255) NOT NULL,
	description VARCHAR(255) NULL
);

CREATE TABLE virtualServers (
	id INTEGER NOT NULL PRIMARY KEY autoincrement,
	veId INTEGER NOT NULL,
	ipAddress VARCHAR(255) NOT NULL,
	hostName VARCHAR(255) NOT NULL,
	veState INTEGER NOT NULL,
	hwServerId INTEGER NOT NULL
);

COMMIT;
