<div id="hwServersList"></div>

<script type="text/javascript">
Ext.onReady(function(){

	function columnHostNameRenderer(hostName, metadata, record) {
		return "<a href='/admin/hardware-server/show/id/" + record.data.id + "'>" + hostName + "</a>";
	}
		
	function addHwServer() {
		alert('implement adding');
	}
	
	function removeHwServer() {
		var selectedItem = Ext.getCmp('hwServersGrid').getSelectionModel().getSelected();
		
		if (!selectedItem) {
			Ext.MessageBox.show({
				title: 'Error',
				msg: 'Please select a server.',
				buttons: Ext.Msg.OK,
				icon: Ext.MessageBox.ERROR
			});
			
			return ;
		}
		
		Ext.MessageBox.confirm('Confirm', 'Are you sure you want to remove server <b>' + selectedItem.get('hostName') + '</b>?', function(button, text) {
			if ('yes' == button) {				
				Ext.Ajax.request({
					url: '/admin/hardware-server/delete',
					success: function(response) {
						var result = Ext.util.JSON.decode(response.responseText);
						
						if (!result.success) {
							Ext.MessageBox.show({
								title: 'Error',
								msg: 'Server deletion request failed.',
								buttons: Ext.Msg.OK,
								icon: Ext.MessageBox.ERROR
							});
						
							return ;
						}
						
						document.location.href = '/admin/hardware-server/list';
					},
					params: { id: selectedItem.get('id') }
				});
			}
		});
	}
	
    var hwServersJsonData = <?php echo $this->hwServersJsonData; ?>;

    var store = new Ext.data.SimpleStore({
        fields: [
           { name: 'id' },
           { name: 'hostName' }
        ]
    });
    
    store.loadData(hwServersJsonData);

    var selectionModel = new Ext.grid.CheckboxSelectionModel({ singleSelect: true });
    
    var grid = new Ext.grid.GridPanel({
    	id: 'hwServersGrid',
        store: store,
        cm: new Ext.grid.ColumnModel([
        	selectionModel, 
        	{ id: 'hostName', header: "Host name", renderer: columnHostNameRenderer, sortable: true, dataIndex: 'hostName' }
        ]),
        sm: selectionModel,
        stripeRows: true,
        autoExpandColumn: 'hostName',
        autoHeight: true,
        autoWidth: true,
        stripeRows: true,
        frame: true,
        tbar: [{
        	text: 'Add server',
        	handler: addHwServer,
        	cls: 'x-btn-text-icon addHwServer'
		}, {
        	text: 'Remove server',
        	handler: removeHwServer,
        	cls: 'x-btn-text-icon removeHwServer'
		}]
    });
    
    grid.render('hwServersList');
});
</script>