<div id="hwServersList"></div>

<script type="text/javascript">
Ext.onReady(function(){

	function columnHostNameRenderer(hostName, metadata, record) {
		return "<a href='/admin/hardware-server/show/id/" + record.data.id + "'>" + hostName + "</a>";
	}
		
	function addHwServer() {
		alert('implement adding');
	}
	
	function removeHwServer() {
		alert('implement deletion');
	}
	
    var hwServersJsonData = <?php echo $this->hwServersJsonData; ?>;

    // create the data store
    var store = new Ext.data.SimpleStore({
        fields: [
           { name: 'id' },
           { name: 'hostName' }
        ]
    });
    
    store.loadData(hwServersJsonData);

    var selectionModel = new Ext.grid.CheckboxSelectionModel();
    
    // create the Grid
    var grid = new Ext.grid.GridPanel({
        store: store,
        cm: new Ext.grid.ColumnModel([
        	selectionModel, 
        	{ id: 'hostName', header: "Host name", renderer: columnHostNameRenderer, sortable: true, dataIndex: 'hostName' }
        ]),
        sm: selectionModel,
        stripeRows: true,
        autoExpandColumn: 'hostName',
        autoHeight: true,
        autoWidth: true,
        stripeRows: true,
        frame: true,
        tbar: [{
        	text: 'Add server',
        	handler: addHwServer,
        	cls: 'x-btn-text-icon addHwServer'
		}, {
        	text: 'Remove server',
        	handler: removeHwServer,
        	cls: 'x-btn-text-icon removeHwServer'
		}]
    });

    grid.render('hwServersList');

    grid.getSelectionModel().selectFirstRow();
});
</script>