<div id="layoutErrorBox">	
	<fieldset>
		<legend>Error</legend>
		
			<table border="0" cellspacing="1" cellpadding="5">
				<tr>
					<th>Message</th>
					<td><?php echo $this->escape($this->exception->getMessage()); ?></td>
				</tr>
				
				<tr>
					<th>Code</th>
					<td><?php echo $this->escape($this->exception->getCode()); ?></td>
				</tr>
				
				<tr>
					<th>File</th>
					<td><?php echo $this->escape($this->exception->getFile()); ?></td>
				</tr>
				
				<tr>
					<th>Line</th>
					<td><?php echo $this->escape($this->exception->getLine()); ?></td>
				</tr>
				
				<tr>
					<th>Trace</th>
					<td><?php echo nl2br(($this->exception->getTraceAsString())); ?></td>
				</tr>
			</table>
			
	</fieldset>
</div>