<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->escape($this->pageTitle) . " - $this->productName $this->productVersion "; ?></title>
	<link rel="shortcut icon" href="/images/favicon.ico"/>	

	<script type="text/javascript" src="/ext/adapter/ext/ext-base.js"></script>
	<script type="text/javascript" src="/ext/ext-all.js"></script>
	<link rel="stylesheet" type="text/css" href="/ext/resources/css/ext-all.css">

	<link rel="stylesheet" type="text/css" href="/skins/common.css?2"/>
	<link rel="stylesheet" type="text/css" href="/skins/win_xp/styles.css?2"/>
	<script type="text/javascript" src="/js/namespaces.js"></script>
	<script type="text/javascript" src="/js/layouts/abstract.js"></script>
</head>
<body>

	<div id="panelHeader">
		<div id="layoutLogo">
			<div id="layoutLogoInner">
				<img src="/skins/win_xp/images/logo.gif">
				<?php echo "$this->productName $this->productVersion"; ?>
			</div>
		</div>
		
		<div id="layoutCopyright">
			<div id="layoutCopyrightInner">
				&copy; Copyright 2008 SoftUnity.<br/>
				All Rights Reserved.
			</div>
		</div>
	</div>