<?php echo $this->render('_header.phtml'); ?>
	
	<?php echo $this->jsFile('/js/layouts/admin.js'); ?>

	<div id="panelMenu">
		<?php echo $this->layout()->menu; ?>
	</div>
	
	<div id="panelContent">
		<div class="x-panel-header" id="rightPanelHeader"><?php echo $this->escape($this->pageTitle); ?></div>
		<div id="panelContentInner">
			<?php echo $this->layout()->content; ?>
		</div>
	</div>

<?php echo $this->render('_footer.phtml'); ?>