<?php echo $this->jsFile('/js/views/admin/dashboard/index.js'); ?>


<script type="text/javascript">
	Owp.Views.Admin.Dashboard.Index.shortcuts = <?php echo $this->shortcuts; ?>;
</script>

<div id="dashboardIntro">
	<div class="x-panel-body" style="padding: 10px;">
		OpenVZ Web Panel is a GUI web-based frontend for controlling of hardware 
		servers with OpenVZ virtualization technology.
	</div>
</div>

<div id="dashboardFirstSteps" style="padding-top: 10px;">
	<div class="x-panel-body" style="padding: 10px;">
		The following guide can help you to made first steps in Web Panel:
		<ul style="list-style-type: disc; padding-left: 20px;">
			<li>Go to hardware servers list</li>
			<li>Connect new hardware server</li>
			<li>Check VPS list</li>
			<li>Add/remove VPS</li>
			<li>Start/stop VPS</li>
			<li>Configure VPS parameters</li>
		</ul>
	</div>
</div>

<div id="dashboardShortcuts" style="padding-top: 10px;"></div>
