<div id="dashboardIntro">
	<div class="x-panel-body" style="padding: 10px;">
		OpenVZ Web Panel is a GUI web-based frontend for controlling of hardware 
		servers with OpenVZ virtualization technology.
	</div>
</div>

<div id="dashboardFirstSteps" style="padding-top: 10px;">
	<div class="x-panel-body" style="padding: 10px;">
		The following guide can help you to made first steps in Web Panel:
		<ul style="list-style-type: disc; padding-left: 20px;">
			<li>Go to hardware servers list</li>
			<li>Connect new hardware server</li>
			<li>Check VPS list</li>
			<li>Add/remove VPS</li>
			<li>Start/stop VPS</li>
			<li>Configure VPS parameters</li>
		</ul>
	</div>
</div>

<div id="dashboardCommonOperations" style="padding-top: 10px;">
	<div class="x-panel-body" style="padding: 10px;">
		<ul style="list-style-type: disc; padding-left: 20px;">
			<li>Hardware servers list</li>
			<li>Add hardware server</li>
			<li>VPS list</li>
			<li>Add VPS</li>
			<li>Configure VPS parameters</li>
		</ul>
	</div>
</div>

<script type="text/javascript">
Ext.onReady(function() {
	var dashboardIntro = new Ext.Panel({
		title: 'Intro',
		applyTo: 'dashboardIntro',
		collapsible: true
	});
	
	var dashboardFirstSteps = new Ext.Panel({
		title: 'First steps',
		applyTo: 'dashboardFirstSteps',
		collapsible: true
	});
	
	var dashboardCommonOperations = new Ext.Panel({
		title: 'Common operations',
		applyTo: 'dashboardCommonOperations',
		collapsible: true
	});
});
</script>